export const CREATE_ADDRESS = "CREATE_ADDRESS";
export const GET_ADDRESS = "GET_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";

export const GET_PROVINSI = "GET_PROVINSI";
export const GET_KABUPATEN = "GET_KABUPATEN";
export const GET_KECAMATAN = "GET_KECAMATAN";
export const GET_KELURAHAN = "GGET_KELURAHAN ";

export const SUCCESS = "SUCCESS";
export const LOADING = "LOADING";
export const ERROR = "ERROR";
export const CLEAR_ADDRESS = "CLEAR_ADDRESS";

export const SET_FORM_ADDRESS = "SET_FORM_ADDRESS";
export const SET_FORM_DEFAULT = "SET_FORM_DEFAULT";
